In [4]:
import  numpy as np

# إنشاء مصفوفة مكونة من 15 floats باستخدام الدالة linspace.

In [5]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# إنشاء مصفوفة ثلاثية الأبعاد (3D) بشكل (2, 2, 3) تحتوي الأربع مصفوفات التالية:



In [6]:
array_3d = np.array([
    [ [1.1, 2.1, 3.1], [4.1, 5.1, 6.1] ],
    [ [7.1, 8.1, 9.1], [10.1, 11.1, 12.1] ]
])
array_3d.shape


(2, 2, 3)

# طباعة جميع خصائص المصفوفة: (type, datatype, shape, size, dimension).


In [7]:
print("type of array: " ,type(array_3d))
print("Data Type: " ,array_3d.dtype)
print("shape " ,array_3d.shape)
print("size " ,array_3d.size)
print("dimensions " ,array_3d.ndim)

type of array:  <class 'numpy.ndarray'>
Data Type:  float64
shape  (2, 2, 3)
size  12
dimensions  3


# تعديل المصفوفة التي أنشأتها سابقًا لتكون ذات أربعة أبعاد (4D) مع طباعة (dimension و shape).


In [8]:
array_4d = np.array(array_3d, ndmin=4)
print("the dimensions of new array " ,array_4d.ndim)
print("shape of new array" ,array_4d.shape)

the dimensions of new array  4
shape of new array (1, 2, 2, 3)


# تعديل نوع المصفوفة التي أنشأتها سابقًا لتكون من نوع integer.



In [9]:
array_int = array_4d.astype(int)
print(array_int)
array_int.dtype


[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


dtype('int64')

#طباعة جميع عناصر المصفوفة باستخدام ()nditer.


In [10]:
for x in np.nditer(array_int):
  print(x, end= ' ')

1 2 3 4 5 6 7 8 9 10 11 12 

#طباعة العنصر رقم 8 في المصفوفة.



In [11]:
print(array_int[0, 1, 0, 1])

8


#طباعة العنصر رقم 5 ورقم 6 في المصفوفة.



In [12]:
print(array_int[0, 0, 1, 1:])


[5 6]


#البحث عن العنصر رقم 8 في المصفوفة باستخدام ()where.



In [13]:
print(np.where(array_int == 8))

(array([0]), array([1]), array([0]), array([1]))


#تعديل شكل المصفوفة السابقة لتكون بالشكل التالي:



In [14]:
'''
array([
[[ 1, 2],
[ 3,  4],
[ 5,  6]],

[[ 7,  8],
[ 9, 10],
[11, 12]]
])
'''

'\narray([\n[[ 1, 2],\n[ 3,  4],\n[ 5,  6]],\n\n[[ 7,  8],\n[ 9, 10],\n[11, 12]]\n])\n'

In [15]:
array_int.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [16]:
array_int

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

#دمج المصفوفتين التالية بدون تحديد axis:


In [17]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_arrays = np.concatenate((arr1, arr2))
print(joined_arrays)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


#دمج المصفوفتين في السؤال السابق بناءً على الصفوف (axis = 1).


In [18]:
joined_arrays2 = np.concatenate((arr1, arr2), axis = 1)
print(joined_arrays2)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# فصل المصفوفة بالسؤال السابق إلى مصفوفتين، بحيث تحتوي كل مصفوفة على 4 مصفوفات مع تحديد (axis = 1).

In [19]:
split_joined_arrays = np.array_split(joined_arrays, 2, axis = 1)
print(split_joined_arrays)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
